CONCAT(
    'These figures describe trading for a single tech stock ',
        'for a 1 hour period between ',
        DATE_FORMAT(`start`, 'yyyy.MM.dd HH:mm:ss'),
            ' and ',
        DATE_FORMAT(`end`, 'yyyy.MM.dd HH:mm:ss'),
    '.\n\n',
    'The number of stocks sold was ',
        CAST(`volume` AS STRING),
    '\n',
    'Trading started at the start of the hour at ',
        CAST(`open` AS STRING),
    ' and finished the hour at ',
        CAST(`close` AS STRING),
    '\n',
    'The highest price during the hour was ',
        CAST(ROUND(`high`, 2) AS STRING),
    '\n',
    'The lowest price was during the hour was ',
        CAST(ROUND(`low`, 2) AS STRING),
    '\n',
    'The average (mean) price was ',
        CAST(ROUND(`mean`, 2) AS STRING),
    '\n',
    'The population variance was ',
        CAST(ROUND(`var_pop`, 3) AS STRING),
    '\n',
    'The sample variance was ',
        CAST(ROUND(`var_samp`, 3) AS STRING),
    '\n',
    'The population standard deviation was ',
        CAST(ROUND(`stddev_pop`, 3) AS STRING),
    '\n',
    'The sample standard deviation was ',
        CAST(ROUND(`stddev_samp`, 3) AS STRING),
    '\n\n',
    'What can we tell about the trading from this data? ',
    'Generate an explanation suitable for someone who is ',
        'not familiar with financial or statistical jargon.'
)