apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: stock-prices-ibm
  namespace: event-automation
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  topicName: STOCK.PRICES.IBM
  partitions: 1
  replicas: 1
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: stock-prices-ibm-output
  namespace: event-automation
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  topicName: STOCK.PRICES.IBM.SUMMARIES
  partitions: 1
  replicas: 1
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
