apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: weather-ibm-hursley
  namespace: event-automation
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  topicName: WEATHER.IBM.HURSLEY
  partitions: 1
  replicas: 3
  config:
    min.insync.replicas: '2'
    retention.ms: '2592000000'

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: weather-ibm-hursley-output
  namespace: event-automation
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  topicName: WEATHER.IBM.HURSLEY.SUMMARIES
  partitions: 1
  replicas: 3
  config:
    min.insync.replicas: '2'
    retention.ms: '2592000000'
